# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='databases.Database', verbose_name='Database'),
        ),
    ]
