# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-20 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_database_creator'),
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_once', models.BooleanField(default=False, verbose_name='\xdanica vez')),
                ('crontab_rule', models.CharField(max_length=100, verbose_name='Regla de crontab')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.Database', verbose_name='Base de datos')),
            ],
        ),
        migrations.AddField(
            model_name='backup',
            name='scheduled_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='backups.ScheduledBackup', verbose_name='Agenda'),
        ),
    ]
