# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteDatabase',
            fields=[
                ('database_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='databases.Database')),
                ('host', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
            ],
            bases=('databases.database',),
        ),
        migrations.CreateModel(
            name='SqliteBackend',
            fields=[
                ('database_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='databases.Database')),
                ('path', models.CharField(max_length=100)),
            ],
            bases=('databases.database',),
        ),
        migrations.CreateModel(
            name='MysqlBackend',
            fields=[
                ('remotedatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='databases.RemoteDatabase')),
            ],
            bases=('databases.remotedatabase',),
        ),
        migrations.CreateModel(
            name='PsqlBackend',
            fields=[
                ('remotedatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='databases.RemoteDatabase')),
            ],
            bases=('databases.remotedatabase',),
        ),
    ]
